# Default values for grpc-practice-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: psycore/grpc-practice-server
  tag: 3
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 10010
  targetPort: 10000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
#    nginx.ingress.kubernetes.io/canary: "true"
#    nginx.ingress.kubernetes.io/canary-by-header: "canary"
#    nginx.ingress.kubernetes.io/canary-weight: "20"
  paths:
    - /hello.HelloService/SayHello
  hosts:
    - psy.cn
  tls:
    - secretName: psycn
      hosts:
        - psy.cn

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
# requests:
#  cpu: 100m
#  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
